py main.py 2> error.log
exit